[[rule]]
id = "case_has_default_branch"

[[rule]]
id = "always_comb_uses_blocking"

[[rule]]
id = "nets_not_left_unused"

[[rule]]
id = "params_not_left_unused"

[[rule]]
id = "vars_not_left_unused"

[[rule]]
id = "ports_not_left_unused"

[[rule]]
id = "net_names_lower_snake"

[[rule]]
id = "var_names_lower_snake"

[[rule]]
id = "disable_targets_fork_only"

[[rule]]
id = "default_nettype_begins_with_none"

[[rule]]
id = "default_nettype_ends_with_wire"

[[rule]]
id = "always_is_structured"

[[rule]]
id = "sensitivity_list_uses_commas"

[[rule]]
id = "macros_close_with_undef"

[[rule]]
id = "macros_use_module_prefix"

[[rule]]
id = "macros_not_unused"

[[rule]]
id = "macro_names_uppercase"

[[rule]]
id = "one_module_per_file"

[[rule]]
id = "module_name_matches_filename"

[[rule]]
id = "module_names_lower_snake"

[[rule]]
id = "parameter_names_uppercase"

[[rule]]
id = "localparam_names_uppercase"

[[rule]]
id = "port_names_lower_snake"

[[rule]]
id = "port_names_have_direction_suffix"

[[rule]]
id = "always_ff_uses_nonblocking"

[[rule]]
id = "functions_marked_automatic_or_static"

[[rule]]
id = "functions_explicit_return_type"

[[rule]]
id = "functions_explicit_arg_types"

[[rule]]
id = "tasks_explicit_arg_types"

[[rule]]
id = "functions_args_have_direction"

[[rule]]
id = "localparam_has_type"

[[rule]]
id = "enum_type_names_lower_snake_e"

[[rule]]
id = "enum_values_uppercase"

[[rule]]
id = "localparams_not_left_unused"

[[rule]]
id = "typedef_names_lower_snake_t"

[[rule]]
id = "parameter_has_type"
