[defaults]
timeout_ms_per_file = 6000

[plugin]
cmd = "python3"
args = ["-u", "-B"]

[[rule]]
id = "flow.multiple_nonblocking"
stage = "ast"

[[rule]]
id = "format.begin_required"
stage = "pp_text"

[[rule]]
id = "case.missing_default"
stage = "cst"

[[rule]]
id = "lang.case_requires_unique"
stage = "cst"

[[rule]]
id = "comb.nb_in_alwayscomb"
stage = "cst"

[[rule]]
id = "decl.unused.net"
stage = "ast"

[[rule]]
id = "decl.unused.param"
stage = "ast"

[[rule]]
id = "decl.unused.var"
stage = "ast"

[[rule]]
id = "lang.default_nettype_missing"
stage = "raw_text"

[[rule]]
id = "lang.default_nettype_none"
stage = "raw_text"

[[rule]]
id = "lang.default_nettype_placement"
stage = "raw_text"

[[rule]]
id = "lang.default_nettype_reset"
stage = "raw_text"

[[rule]]
id = "check.dv_macro_required"
stage = "raw_text"

[[rule]]
id = "dpi.export_prefix"
stage = "raw_text"

[[rule]]
id = "dpi.import_prefix"
stage = "raw_text"

[[rule]]
id = "flow.no_disable_fork_label"
stage = "raw_text"

[[rule]]
id = "flow.no_fork_label"
stage = "raw_text"

[[rule]]
id = "flow.spinwait_macro_required"
stage = "raw_text"

[[rule]]
id = "flow.wait_fork_isolation"
stage = "raw_text"

[[rule]]
id = "flow.wait_macro_required"
stage = "raw_text"

[[rule]]
id = "lang.no_program_construct"
stage = "raw_text"

[[rule]]
id = "log.allowed_verbosity"
stage = "raw_text"

[[rule]]
id = "log.no_display"
stage = "raw_text"

[[rule]]
id = "log.no_none_full"
stage = "raw_text"

[[rule]]
id = "log.no_uvm_report_api"
stage = "raw_text"

[[rule]]
id = "log.no_uvm_warning"
stage = "raw_text"

[[rule]]
id = "log.uvm_arg_macro"
stage = "raw_text"

[[rule]]
id = "macro.dv_prefix_header_only"
stage = "raw_text"

[[rule]]
id = "macro.guard_required"
stage = "raw_text"

[[rule]]
id = "macro.missing_undef"
stage = "raw_text"

[[rule]]
id = "macro.module_prefix"
stage = "raw_text"

[[rule]]
id = "macro.no_local_guard"
stage = "raw_text"

[[rule]]
id = "rand.dv_macro_required"
stage = "raw_text"

[[rule]]
id = "rand.dv_macro_with_required"
stage = "raw_text"

[[rule]]
id = "scoreboard.dv_eot_required"
stage = "raw_text"

[[rule]]
id = "seq.no_uvm_do"
stage = "raw_text"

[[rule]]
id = "style.function_scope"
stage = "raw_text"

[[rule]]
id = "format.end_else_inline"
stage = "pp_text"

[[rule]]
id = "format.case_begin_required"
stage = "cst"

[[rule]]
id = "format.indent_multiple_of_two"
stage = "raw_text"

[[rule]]
id = "format.line_continuation_right"
stage = "raw_text"

[[rule]]
id = "format.preproc_left_align"
stage = "raw_text"

[[rule]]
id = "format.line_length"
stage = "raw_text"

[[rule]]
id = "format.call_spacing"
stage = "raw_text"

[[rule]]
id = "format.case_colon_after"
stage = "cst"

[[rule]]
id = "format.case_colon_spacing"
stage = "cst"

[[rule]]
id = "format.comma_space"
stage = "raw_text"

[[rule]]
id = "format.macro_spacing"
stage = "raw_text"

[[rule]]
id = "format.ascii_only"
stage = "raw_text"

[[rule]]
id = "format.final_newline"
stage = "raw_text"

[[rule]]
id = "format.no_tabs"
stage = "raw_text"

[[rule]]
id = "format.no_trailing_whitespace"
stage = "raw_text"

[[rule]]
id = "global.local_define_undef"
stage = "raw_text"

[[rule]]
id = "global.prefer_parameters"
stage = "raw_text"

[[rule]]
id = "header.missing_comment"
stage = "raw_text"

[[rule]]
id = "header.missing_spdx"
stage = "raw_text"

[[rule]]
id = "lang.always_comb_at"
stage = "raw_text"

[[rule]]
id = "lang.always_ff_reset"
stage = "raw_text"

[[rule]]
id = "lang.no_always_latch"
stage = "raw_text"

[[rule]]
id = "lang.no_delays"
stage = "raw_text"

[[rule]]
id = "lang.prefer_always_comb"
stage = "raw_text"

[[rule]]
id = "module.named_ports_required"
stage = "raw_text"

[[rule]]
id = "naming.clk_order"
stage = "ast"

[[rule]]
id = "naming.clk_prefix"
stage = "ast"

[[rule]]
id = "naming.differential_pair"
stage = "ast"

[[rule]]
id = "naming.module_case"
stage = "ast"

[[rule]]
id = "naming.no_numeric_suffix"
stage = "ast"

[[rule]]
id = "naming.parameter_upper"
stage = "ast"

[[rule]]
id = "naming.pipeline_sequence"
stage = "ast"

[[rule]]
id = "naming.port_case"
stage = "ast"

[[rule]]
id = "naming.port_suffix"
stage = "ast"

[[rule]]
id = "naming.rst_active_low"
stage = "ast"

[[rule]]
id = "naming.rst_before_clk"
stage = "ast"

[[rule]]
id = "naming.signal_case"
stage = "ast"

[[rule]]
id = "naming.suffix_order"
stage = "ast"

[[rule]]
id = "module.no_port_wildcard"
stage = "cst"

[[rule]]
id = "package.define_in_package"
stage = "raw_text"

[[rule]]
id = "package.end_mismatch"
stage = "raw_text"

[[rule]]
id = "package.missing_end"
stage = "raw_text"

[[rule]]
id = "package.multiple"
stage = "raw_text"

[[rule]]
id = "seq.blocking_in_alwaysff"
stage = "cst"

[[rule]]
id = "template.raw_text_marker"
stage = "raw_text"

[[rule]]
id = "typedef.enum_lower_snake"
stage = "raw_text"

[[rule]]
id = "typedef.enum_suffix"
stage = "raw_text"

[[rule]]
id = "typedef.enum_value_case"
stage = "raw_text"

[[rule]]
id = "typedef.enum_value_prefix"
stage = "raw_text"

[[rule]]
id = "typedef.type_suffix"
stage = "raw_text"

[[rule]]
id = "width.unsized_base_literal"
stage = "raw_text"

[logging]
level = "info"
stderr_snippet_bytes = 2000
show_stage_events = false
show_plugin_events = false
show_parse_events = false

[svparser]
include_paths = []
defines = []
strip_comments = true
ignore_include = true
allow_incomplete = true

[stages]
enabled = ["raw_text", "pp_text", "cst", "ast"]
required = ["raw_text", "pp_text"]

[transport]
max_request_bytes = 16777216
warn_margin_bytes = 1048576
max_response_bytes = 16777216
on_exceed = "skip"
fail_ci_on_skip = false
[rule_defaults]
"case.missing_default" = "plugins/case_default_required.py"
"check.dv_macro_required" = "plugins/dv_text_rules.py"
"comb.nb_in_alwayscomb" = "plugins/comb_nb_in_alwayscomb.py"
"decl.unused.net" = "plugins/decl_unused_net.py"
"decl.unused.param" = "plugins/decl_unused_param.py"
"decl.unused.var" = "plugins/decl_unused_var.py"
"dpi.export_prefix" = "plugins/dv_text_rules.py"
"dpi.import_prefix" = "plugins/dv_text_rules.py"
"flow.multiple_nonblocking" = "plugins/assignment_rules.py"
"flow.no_disable_fork_label" = "plugins/dv_text_rules.py"
"flow.no_fork_label" = "plugins/dv_text_rules.py"
"flow.spinwait_macro_required" = "plugins/dv_text_rules.py"
"flow.wait_fork_isolation" = "plugins/dv_text_rules.py"
"flow.wait_macro_required" = "plugins/dv_text_rules.py"
"format.ascii_only" = "plugins/format_text_basics.py"
"format.begin_required" = "plugins/begin_end_required.py"
"format.call_spacing" = "plugins/format_spacing.py"
"format.case_begin_required" = "plugins/format_case_begin_cst.py"
"format.case_colon_after" = "plugins/format_spacing.py"
"format.case_colon_spacing" = "plugins/format_spacing.py"
"format.comma_space" = "plugins/format_spacing.py"
"format.end_else_inline" = "plugins/end_else_same_line.py"
"format.final_newline" = "plugins/format_text_basics.py"
"format.indent_multiple_of_two" = "plugins/format_indent_rules.py"
"format.line_continuation_right" = "plugins/format_indent_rules.py"
"format.line_length" = "plugins/format_line_length.py"
"format.macro_spacing" = "plugins/format_spacing.py"
"format.no_tabs" = "plugins/format_text_basics.py"
"format.no_trailing_whitespace" = "plugins/format_text_basics.py"
"format.preproc_left_align" = "plugins/format_indent_rules.py"
"global.local_define_undef" = "plugins/global_define_rules.py"
"global.prefer_parameters" = "plugins/global_define_rules.py"
"header.missing_comment" = "plugins/header_comment_rule.py"
"header.missing_spdx" = "plugins/header_comment_rule.py"
"lang.always_comb_at" = "plugins/lang_construct_rules.py"
"lang.always_ff_reset" = "plugins/lang_construct_rules.py"
"lang.case_requires_unique" = "plugins/case_unique_required.py"
"lang.default_nettype_missing" = "plugins/default_nettype_rule.py"
"lang.default_nettype_none" = "plugins/default_nettype_rule.py"
"lang.default_nettype_placement" = "plugins/default_nettype_rule.py"
"lang.default_nettype_reset" = "plugins/default_nettype_rule.py"
"lang.no_always_latch" = "plugins/lang_construct_rules.py"
"lang.no_delays" = "plugins/lang_construct_rules.py"
"lang.no_program_construct" = "plugins/dv_text_rules.py"
"lang.prefer_always_comb" = "plugins/lang_construct_rules.py"
"log.allowed_verbosity" = "plugins/dv_text_rules.py"
"log.no_display" = "plugins/dv_text_rules.py"
"log.no_none_full" = "plugins/dv_text_rules.py"
"log.no_uvm_report_api" = "plugins/dv_text_rules.py"
"log.no_uvm_warning" = "plugins/dv_text_rules.py"
"log.uvm_arg_macro" = "plugins/dv_text_rules.py"
"macro.dv_prefix_header_only" = "plugins/dv_text_rules.py"
"macro.guard_required" = "plugins/dv_text_rules.py"
"macro.missing_undef" = "plugins/dv_text_rules.py"
"macro.module_prefix" = "plugins/dv_text_rules.py"
"macro.no_local_guard" = "plugins/dv_text_rules.py"
"module.named_ports_required" = "plugins/module_inst_rules.py"
"module.no_port_wildcard" = "plugins/no_port_wildcard.py"
"naming.clk_order" = "plugins/naming_rules.py"
"naming.clk_prefix" = "plugins/naming_rules.py"
"naming.differential_pair" = "plugins/naming_rules.py"
"naming.module_case" = "plugins/naming_rules.py"
"naming.no_numeric_suffix" = "plugins/naming_rules.py"
"naming.parameter_upper" = "plugins/naming_rules.py"
"naming.pipeline_sequence" = "plugins/naming_rules.py"
"naming.port_case" = "plugins/naming_rules.py"
"naming.port_suffix" = "plugins/naming_rules.py"
"naming.rst_active_low" = "plugins/naming_rules.py"
"naming.rst_before_clk" = "plugins/naming_rules.py"
"naming.signal_case" = "plugins/naming_rules.py"
"naming.suffix_order" = "plugins/naming_rules.py"
"package.define_in_package" = "plugins/package_rules.py"
"package.end_mismatch" = "plugins/package_rules.py"
"package.missing_end" = "plugins/package_rules.py"
"package.multiple" = "plugins/package_rules.py"
"rand.dv_macro_required" = "plugins/dv_text_rules.py"
"rand.dv_macro_with_required" = "plugins/dv_text_rules.py"
"scoreboard.dv_eot_required" = "plugins/dv_text_rules.py"
"seq.blocking_in_alwaysff" = "plugins/seq_blocking_in_alwaysff.py"
"seq.no_uvm_do" = "plugins/dv_text_rules.py"
"style.function_scope" = "plugins/dv_text_rules.py"
"template.raw_text_marker" = "plugins/template_raw_text_rule.py"
"typedef.enum_lower_snake" = "plugins/typedef_naming_rules.py"
"typedef.enum_suffix" = "plugins/typedef_naming_rules.py"
"typedef.enum_value_case" = "plugins/typedef_naming_rules.py"
"typedef.enum_value_prefix" = "plugins/typedef_naming_rules.py"
"typedef.type_suffix" = "plugins/typedef_naming_rules.py"
"width.unsized_base_literal" = "plugins/width_literal_rules.py"
