[defaults]
timeout_ms_per_file = 6000

[plugin]
cmd = "python3"
args = ["-u", "-B"]
root = "plugins"

[logging]
level = "info"
stderr_snippet_bytes = 2000
show_stage_events = false
show_plugin_events = false
show_parse_events = false

[svparser]
include_paths = []
defines = []
strip_comments = true
ignore_include = true
allow_incomplete = true

[stages]
enabled = ["raw_text", "pp_text", "cst", "ast"]
required = ["raw_text", "pp_text"]

[transport]
max_request_bytes = 16777216
warn_margin_bytes = 1048576
max_response_bytes = 16777216
on_exceed = "skip"
fail_ci_on_skip = false

[[rule]]
id = "case.missing_default"

[[rule]]
id = "check.dv_macro_required"

[[rule]]
id = "macro.dv_prefix_header_only"

[[rule]]
id = "macro.guard_required"

[[rule]]
id = "macro.missing_undef"

[[rule]]
id = "macro.module_prefix"

[[rule]]
id = "macro.no_local_guard"

[[rule]]
id = "module.named_ports_required"

[[rule]]
id = "module.no_port_wildcard"

[[rule]]
id = "naming.clk_order"

[[rule]]
id = "naming.clk_prefix"

[[rule]]
id = "naming.differential_pair"

[[rule]]
id = "naming.module_case"

[[rule]]
id = "naming.no_numeric_suffix"

[[rule]]
id = "naming.parameter_upper"

[[rule]]
id = "naming.pipeline_sequence"

[[rule]]
id = "naming.port_case"

[[rule]]
id = "naming.port_suffix"

[[rule]]
id = "naming.rst_active_low"

[[rule]]
id = "naming.rst_before_clk"

[[rule]]
id = "naming.signal_case"

[[rule]]
id = "naming.suffix_order"

[[rule]]
id = "package.define_in_package"

[[rule]]
id = "package.end_mismatch"

[[rule]]
id = "package.missing_end"

[[rule]]
id = "package.multiple"

[[rule]]
id = "rand.dv_macro_required"

[[rule]]
id = "rand.dv_macro_with_required"

[[rule]]
id = "scoreboard.dv_eot_required"

[[rule]]
id = "seq.blocking_in_alwaysff"

[[rule]]
id = "seq.no_uvm_do"

[[rule]]
id = "style.function_scope"

[[rule]]
id = "template.raw_text_marker"

[[rule]]
id = "typedef.enum_lower_snake"

[[rule]]
id = "typedef.enum_suffix"

[[rule]]
id = "typedef.enum_value_case"

[[rule]]
id = "typedef.enum_value_prefix"

[[rule]]
id = "typedef.type_suffix"

[[rule]]
id = "width.unsized_base_literal"
