[[rule]]
id = "require_case_default"

[[rule]]
id = "forbid_always_comb_nb"

[[rule]]
id = "forbid_unused_net"

[[rule]]
id = "forbid_unused_param"

[[rule]]
id = "forbid_unused_var"

[[rule]]
id = "require_net_lower_snake"

[[rule]]
id = "require_var_lower_snake"

[[rule]]
id = "forbid_disable_label"

[[rule]]
id = "require_default_nettype_head_none"

[[rule]]
id = "require_default_nettype_tail_wire"

[[rule]]
id = "require_structured_always"
stage = "cst"

[[rule]]
id = "require_macro_undef"

[[rule]]
id = "require_macro_module_prefix"

[[rule]]
id = "forbid_unused_macro"

[[rule]]
id = "require_define_uppercase"

[[rule]]
id = "require_named_ports"

[[rule]]
id = "require_single_module"

[[rule]]
id = "require_module_filename_match"

[[rule]]
id = "naming_module_lower_snake"

[[rule]]
id = "require_param_uppercase"

[[rule]]
id = "require_localparam_uppercase"

[[rule]]
id = "naming_port_lower_snake"

[[rule]]
id = "require_port_direction_suffix"

[[rule]]
id = "forbid_define_in_package"

[[rule]]
id = "require_single_package"

[[rule]]
id = "forbid_always_ff_blocking"

[[rule]]
id = "require_function_scope"

[[rule]]
id = "require_enum_name_lower_snake_e"
stage = "cst"

[[rule]]
id = "require_enum_value_upper"
stage = "cst"

[[rule]]
id = "require_typedef_name_lower_snake_t"
stage = "cst"
