[[rule]]
id = "case_require_default"

[[rule]]
id = "always_comb_no_nonblocking"

[[rule]]
id = "decl_no_unused_net"

[[rule]]
id = "decl_no_unused_param"

[[rule]]
id = "decl_no_unused_var"

[[rule]]
id = "naming_net_lower_snake"

[[rule]]
id = "naming_var_lower_snake"

[[rule]]
id = "flow_no_disable_label"

[[rule]]
id = "lang_default_nettype_require_prologue_none"

[[rule]]
id = "lang_default_nettype_require_epilogue_wire"

[[rule]]
id = "lang_always_require_structured"
stage = "cst"

[[rule]]
id = "macro_require_trailing_undef"

[[rule]]
id = "macro_require_module_prefix"

[[rule]]
id = "macro_no_unused_macro"

[[rule]]
id = "macro_define_uppercase"

[[rule]]
id = "module_require_named_ports"

[[rule]]
id = "module_single_module_per_file"

[[rule]]
id = "module_name_matches_file"

[[rule]]
id = "naming_module_lower_snake"

[[rule]]
id = "naming_parameter_uppercase"

[[rule]]
id = "naming_localparam_uppercase"

[[rule]]
id = "naming_port_lower_snake"

[[rule]]
id = "naming_port_direction_suffix"

[[rule]]
id = "package_no_define_in_package"

[[rule]]
id = "package_single_package"

[[rule]]
id = "always_ff_no_blocking"

[[rule]]
id = "function_require_scope"

[[rule]]
id = "typedef_enum_name_lower_snake_e"
stage = "cst"

[[rule]]
id = "typedef_enum_value_upper"
stage = "cst"

[[rule]]
id = "typedef_type_name_lower_snake_t"
stage = "cst"
