[[rule]]
id = "case.require_default"

[[rule]]
id = "comb.no_nb_in_always_comb"

[[rule]]
id = "decl.no_unused_net"

[[rule]]
id = "decl.no_unused_param"

[[rule]]
id = "decl.no_unused_var"

[[rule]]
id = "naming.net_lower_snake"

[[rule]]
id = "naming.var_lower_snake"

[[rule]]
id = "flow.no_multiple_nb_assign"

[[rule]]
id = "flow.no_disable_label"

[[rule]]
id = "lang.default_nettype.require_prologue_none"

[[rule]]
id = "lang.default_nettype.require_epilogue_wire"

[[rule]]
id = "lang.prefer_always_comb"

[[rule]]
id = "lang.always.require_structured"
stage = "cst"

[[rule]]
id = "macro.require_trailing_undef"

[[rule]]
id = "macro.require_module_prefix"

[[rule]]
id = "macro.no_unused_macro"

[[rule]]
id = "macro.define_uppercase"

[[rule]]
id = "module.require_named_ports"

[[rule]]
id = "module.single_module_per_file"

[[rule]]
id = "module.name_matches_file"

[[rule]]
id = "naming.module_lower_snake"

[[rule]]
id = "naming.parameter_uppercase"

[[rule]]
id = "naming.localparam_lower_snake"

[[rule]]
id = "naming.port_lower_snake"

[[rule]]
id = "naming.port_direction_suffix"

[[rule]]
id = "package.require_defines_in_pkg"

[[rule]]
id = "package.single_package"

[[rule]]
id = "seq.no_blocking_in_always_ff"

[[rule]]
id = "style.require_function_scope"

[[rule]]
id = "typedef.enum_name_lower_snake_e"
stage = "cst"

[[rule]]
id = "typedef.enum_value_upper"
stage = "cst"

[[rule]]
id = "typedef.type_name_suffix_t"
stage = "cst"
