[[rule]]
id = "case.missing_default"

[[rule]]
id = "comb.nb_in_alwayscomb"

[[rule]]
id = "decl.unused_net"

[[rule]]
id = "decl.unused_param"

[[rule]]
id = "decl.unused_var"

[[rule]]
id = "flow.multiple_nonblocking"

[[rule]]
id = "flow.no_disable_fork_label"

[[rule]]
id = "flow.no_fork_label"

[[rule]]
id = "global.local_define_undef"

[[rule]]
id = "lang.default_nettype_missing"

[[rule]]
id = "lang.default_nettype_reset"

[[rule]]
id = "lang.prefer_always_comb"

[[rule]]
id = "macro.missing_undef"

[[rule]]
id = "macro.module_prefix"

[[rule]]
id = "module.named_ports_required"

[[rule]]
id = "naming.module_case"

[[rule]]
id = "naming.parameter_upper"

[[rule]]
id = "naming.port_case"

[[rule]]
id = "naming.port_suffix"

[[rule]]
id = "naming.signal_case"

[[rule]]
id = "package.define_in_package"

[[rule]]
id = "package.multiple"

[[rule]]
id = "seq.blocking_in_alwaysff"

[[rule]]
id = "style.function_scope"

[[rule]]
id = "typedef.enum_lower_snake"

[[rule]]
id = "typedef.enum_suffix"

[[rule]]
id = "typedef.enum_value_case"

[[rule]]
id = "typedef.enum_value_prefix"

[[rule]]
id = "typedef.type_suffix"
